version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      # EKS(쿠버네티스)에 명령을 내릴 도구(kubectl) 설치
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.0/2024-09-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 416225317325.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=416225317325.dkr.ecr.us-east-2.amazonaws.com/hcoh-library-proj
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd librarysystem_front
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # ----------------------------------------------------
      # ▼▼▼ 여기가 중요합니다! (EKS 연결 및 배포) ▼▼▼
      # ----------------------------------------------------
      - echo Updating kubeconfig...
      # 방금 만든 클러스터 이름(hcoh-library-cluster)으로 접속 설정
      - aws eks update-kubeconfig --name hcoh-library-cluster --region us-east-2
      
      - echo Deploying to EKS...
      # 주문서(yaml) 파일들을 EKS 주방에 전달!
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - echo Deployment completed!